services:
  redditarchiver:
    build:
      context: .
      dockerfile: Dockerfile.redditarchiver
      args:
        NAME: RedditArchiver
        APP_URL: http://localhost
        REDDIT_CLIENT_ID: $REDDIT_CLIENT_ID
        REDDIT_CLIENT_SECRET: $REDDIT_CLIENT_SECRET
    ports:
      - "5000:5000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
        - front-end:/app/data/static
  revproxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - redditarchiver
    volumes:
        - front-end:/app/data/static

volumes:
    front-end: